SalonBelleza.UI.AppWebAspCore/Controllers/CitaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SalonBelleza.EntidadesDeNegocio;
using SalonBelleza.LogicaDeNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SalonBelleza.UI.AppWebAspCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class CitaController : Controller
    {
        CitaBL citaBL = new CitaBL();
        ClienteBL clienteBL = new ClienteBL();
        UsuarioBL usuarioBL = new UsuarioBL();
        ServicioBL servicioBL = new ServicioBL();
        DetalleCitaBL detalleCitaBL = new DetalleCitaBL();
        // GET: CitaController
        public async Task<IActionResult> Index(Cita pCita = null)
        {
            if (pCita == null)
                pCita = new Cita();
            if (pCita.Top_Aux == 0)
                pCita.Top_Aux = 10;
            else if (pCita.Top_Aux == -1)
                pCita.Top_Aux = 0;
            var taskBuscarCliente = citaBL.BuscarIncluirClienteAsync(pCita);
            var taskObtenerTodosClientes = clienteBL.ObtenerTodosAsync();
            var taskBuscarUsuario = citaBL.BuscarIncluirUsuarioAsync(pCita);
            var taskObtenerTodosUsuarios = usuarioBL.ObtenerTodosAsync();
            var taskBuscarUsuarioCliente = citaBL.BuscarIncluirUsuarioClienteAsync(pCita);
            var citas = await taskBuscarUsuarioCliente;
            ViewBag.Top = pCita.Top_Aux;
            ViewBag.Clientes = await taskObtenerTodosClientes;
            ViewBag.Usuarios = await taskObtenerTodosUsuarios;
            return View(citas);
        }

        // GET: CitaController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var cita = await citaBL.ObtenerPorIdAsync(new Cita { Id = id });
            var taskCliente = clienteBL.ObtenerPorIdAsync(new Cliente { Id = cita.IdCliente });
            var taskUsuario= usuarioBL.ObtenerPorIdAsync(new Usuario { Id = cita.IdUsuario });
            var taskDetalles = detalleCitaBL.BuscarIncluirServicioAsync(new DetalleCita { IdCita = cita.Id });
            cita.Cliente = await taskCliente;
            cita.Usuario = await taskUsuario;
            cita.DetalleCita = await taskDetalles;
            return View(cita);
        }

        // GET: CitaController/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Clientes = await clienteBL.ObtenerTodosAsync();
            ViewBag.Usuarios = await usuarioBL.ObtenerTodosAsync();
            ViewBag.servicios = await servicioBL.ObtenerTodosAsync();
            ViewBag.Error = "";
            return View();
        }

        // POST: CitaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cita pCita)
        {
            try
            {
               // int result = 0;
                int result = await citaBL.CrearAsync(pCita);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Clientes = await clienteBL.ObtenerTodosAsync();
                ViewBag.Usuarios = await usuarioBL.ObtenerTodosAsync();
                ViewBag.servicios = await servicioBL.ObtenerTodosAsync();
                return View(pCita); //si ocurrio un error se redirecciona a la vista create con el parametro
            }
        }

        // GET: CitaController/Edit/5
        public async Task<IActionResult> Edit(Cita pCita)
        {
            var taskObtenerPorId = citaBL.ObtenerPorIdAsync(pCita);
            var taskObtenerTodosClientes = clienteBL.ObtenerTodosAsync();
            var taskObtenerTodosUsuarios = usuarioBL.ObtenerTodosAsync();
            var cita = await taskObtenerPorId;
            ViewBag.Clientes = await taskObtenerTodosClientes;
            ViewBag.Usuarios = await taskObtenerTodosUsuarios;
            ViewBag.Error = "";
            return View(cita);
        }

        // POST: CitaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Cita pCita)
        {
            try
            {
                int result = await citaBL.ModificarAsync(pCita);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Clientes = await clienteBL.ObtenerTodosAsync();
                ViewBag.Usuarios = await usuarioBL.ObtenerTodosAsync();
                return View(pCita);
            }
        }

        // GET: CitaController/Delete/5
        public async Task<IActionResult> Delete(Cita pCita)
        {
            ViewBag.Error = "";
            var cita = await citaBL.ObtenerPorIdAsync(pCita);
            cita.Cliente = await clienteBL.ObtenerPorIdAsync(new Cliente { Id = cita.IdCliente });
            cita.Usuario = await usuarioBL.ObtenerPorIdAsync(new Usuario { Id = cita.IdUsuario });
            return View(cita);
        }

        // POST: CitaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Cita pCita)
        {
            try
            {
                int result = await citaBL.EliminarAsync(pCita);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var cita = await citaBL.ObtenerPorIdAsync(pCita);
                if (cita == null)
                    cita = new Cita();
                if (cita.Id > 0)
                {
                    cita.Cliente = await clienteBL.ObtenerPorIdAsync(new Cliente { Id = cita.IdCliente });
                    cita.Usuario = await usuarioBL.ObtenerPorIdAsync(new Usuario { Id = cita.IdUsuario });
                }
                return View(pCita);
            }
        }

        public IActionResult ManejarTablas()
        {
            return View();
        }
    }
}

SalonBelleza.UI.AppWebAspCore/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
/*********************************/
using SalonBelleza.EntidadesDeNegocio;
using SalonBelleza.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SalonBelleza.UI.AppWebAspCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class ClienteController : Controller
    {
        ClienteBL clienteBL = new ClienteBL();
        // GET: ClienteController
        public async Task<IActionResult> Index(Cliente pCliente = null)
        {
            if (pCliente == null)
                pCliente = new Cliente();
            if (pCliente.Top_Aux == 0)
                pCliente.Top_Aux = 10;
            else if (pCliente.Top_Aux == -1)
                pCliente.Top_Aux = 0;
            var clientes = await clienteBL.BuscarAsync(pCliente);
            ViewBag.Top = pCliente.Top_Aux;
            return View(clientes);
        }

        // GET: ClienteController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var cliente = await clienteBL.ObtenerPorIdAsync(new Cliente { Id = id });
            return View(cliente);
        }

        // GET: ClienteController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cliente pCliente)
        {
            try
            {
                int result = await clienteBL.CrearAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCliente);
            }
        }

        // GET: ClienteController/Edit/5
        public async Task<IActionResult> Edit(Cliente pCliente)
        {
            var cliente = await clienteBL.ObtenerPorIdAsync(pCliente);
            ViewBag.Error = "";
            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Cliente pCliente)
        {
            try
            {
                int result = await clienteBL.ModificarAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCliente);
            }
        }

        // GET: ClienteController/Delete/5
        public async Task<IActionResult> Delete(Cliente pCliente)
        {
            ViewBag.Error = "";
            var cliente = await clienteBL.ObtenerPorIdAsync(pCliente);
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Cliente pCliente)
        {
            try
            {
                int result = await clienteBL.EliminarAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCliente);
            }
        }
    }
}

SalonBelleza.UI.AppWebAspCore/Controllers/RolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
/*********************************/
using SalonBelleza.EntidadesDeNegocio;
using SalonBelleza.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SalonBelleza.UI.AppWebAspCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class RolController : Controller
    {
        RolBL rolBL = new RolBL();
        // GET: RolController
        public async Task<IActionResult> Index(Rol pRol = null) 
        {
            if (pRol == null)
                pRol = new Rol();
            if (pRol.Top_Aux == 0)
                pRol.Top_Aux = 10;
            else if (pRol.Top_Aux == -1)
                pRol.Top_Aux = 0;
            var roles = await rolBL.BuscarAsync(pRol);
            ViewBag.Top = pRol.Top_Aux;
            return View(roles);
        }

        // GET: RolController/Details/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Details(int id) 
        {
            var rol = await rolBL.ObtenerPorIdAsync(new Rol { Id = id });
            return View(rol);
        }

        // GET: RolController/Create
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "ADMINISTRADOR")]
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: RolController/Create
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "ADMINISTRADOR")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rol pRol) 
        {
            try 
            {
                int result = await rolBL.CrearAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        // GET: RolController/Edit/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "ADMINISTRADOR")]
        public async Task <IActionResult> Edit (Rol pRol) 
        {
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            ViewBag.Eroor = "";
            return View(rol);
        }

        // POST: RolController/Edit/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "ADMINISTRADOR")]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, Rol pRol) 
        {
            try 
            {
                int result = await rolBL.ModificarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        // GET: RolController/Delete/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "ADMINISTRADOR")]
        public async Task<IActionResult> Delete(Rol pRol) 
        {
            ViewBag.Error = "";
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            return View(rol);
        }

        // POST: RolController/Delete/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "ADMINISTRADOR")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Rol pRol) 
        {
            try 
            {
                int result = await rolBL.EliminarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }
    }
}

SalonBelleza.UI.AppWebAspCore/Controllers/ServicioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using SalonBelleza.EntidadesDeNegocio;
using SalonBelleza.LogicaDeNegocio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;


namespace SalonBelleza.UI.AppWebAspCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class ServicioController : Controller
    {

        ServicioBL ServicioBL = new ServicioBL();
        // GET: ServicioController
        public async Task<IActionResult> Index(Servicio pServicio = null)
        {
            if (pServicio == null)
                pServicio = new Servicio();
            if (pServicio.Top_Aux == 0)
                pServicio.Top_Aux = 10;
            else if (pServicio.Top_Aux == -1)
                pServicio.Top_Aux = 0;
            var servicios = await ServicioBL.BuscarAsync(pServicio);
            ViewBag.Top = pServicio.Top_Aux;
            return View(servicios);
        }

        // GET: ServicioController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var servicio = await ServicioBL.ObtenerPorIdAsync(new Servicio { Id = id });
            return View(servicio);
        }

        // GET: ServicioController/Create
        public ActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: ServicioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Servicio pServicio)
        {
            try
            {
                int result = await ServicioBL.CrearAsync(pServicio);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pServicio);
            }
        }

        // GET: ServicioController/Edit/5
        public async Task<IActionResult> Edit(Servicio pServicio)
        {
            var servicio = await ServicioBL.ObtenerPorIdAsync(pServicio);
            ViewBag.Error = "";
            return View(servicio);
        }

        // POST: ServicioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Servicio pServicio)
        {
            try
            {
                int result = await ServicioBL.ModificarAsync(pServicio);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pServicio);
            }
        }

        // GET: ServicioController/Delete/5
        public async Task<IActionResult> Delete(Servicio pServicio)
        {
            ViewBag.Error = "";
            var servicio = await ServicioBL.ObtenerPorIdAsync(pServicio);
            return View(servicio);
        }

        // POST: ServicioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Servicio pServicio)
        {
            try
            {
                int result = await ServicioBL.EliminarAsync(pServicio);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pServicio);
            }
        }
    }
}

SalonBelleza.UI.AppWebAspCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Salon de Belleza</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">*@
    <link rel="stylesheet" href="~/css/site.css" />

    <style>
        

        .container {
            padding: 10px;
            background: #7F7FD5;
            background: -webkit-linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
            background: linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
        }

        footer {
            font-family: 'Gothic';
            color: black;
            padding: 30px;
            text-align: center;
            width: 100%;
            height: 40px;
            position: absolute;
            bottom: 0;
            left: 0;
        }

        Cfooter {
            color: #000000;
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 40px;
        }

        .Cfooter {
            color: #000000;
        }

        .navbar-brand {
            color: azure;
        }

        .nav-link {
            color: azure;
        }

        a {
            color: azure;
            font-family: arial;
            text-decoration: none;
        }

            a:hover {
                color: azure;
                font-family: arial;
                text-decoration: none;
            }

        .nav-link {
            color: azure;
            font-family: arial;
            text-decoration: none;
        }

            .nav-link:hover {
                color: azure;
                font-family: arial;
                text-decoration: none;
            }

         body {
            background-size: cover;
            background-repeat: no-repeat;
            height: 100%;
            font-family: 'Numans', sans-serif;
        }
    </style>
</head>
        <body >
            <header>
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><big>Salon de Belleza</big></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                                                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
                                            </svg>
                                            Inicio
                                        </a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Rol" asp-action="Index">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                                                <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                                            </svg>
                                        Rol
                                        </a>
                                    </li>

                                    @if (User.IsInRole("ADMINISTRADOR"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="Index">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                                </svg>
                                                Usuario
                                            </a>
                                        </li>
                                    }
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Cliente" asp-action="Index">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                                            </svg>
                                        Cliente
                                        </a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Servicio" asp-action="Index">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-badge-fill" viewBox="0 0 16 16">
                                                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm4.5 0a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1h-3zM8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm5 2.755C12.146 12.825 10.623 12 8 12s-4.146.826-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z" />
                                            </svg>
                                        Servicio</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Cita" asp-action="Index">

                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-fill" viewBox="0 0 16 16">
                                                <path d="M4 0h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm5.5 1.5v2a1 1 0 0 0 1 1h2l-3-3z" />
                                            </svg>
                                        Cita
                                        </a>

                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="CambiarPassword">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                            </svg>
                                            Cambiar Contraseña
                                        </a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
                                                <path d="M7.5 1v7h1V1h-1z" />
                                                <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z" />
                                            </svg>
                                        Cerrar sesión
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        }


                    </div>
                </nav>
            </header>
            <br>
            <div class="container" style="background-color: #000000; border: 1px ridge #000000; border-radius: 15px 15px 15px 15px ">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <br />

            <footer class="footer text-muted" style="background-color: rgba(0, 0, 0, 0.3);">
                <div class="Cfooter">
                    &copy; 2021 - Salon de Belleza
                </div>
            </footer>
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>